#-----------------------------------------------------------------------------#
# Application Properties #
# inside ./src/main/resources/application.yml
#-----------------------------------------------------------------------------#
# Turn on debug logging to show ConditionEvaluationReport :
debug: true

#-----------------------------------------------------------------------------#