#-----------------------------------------------------------------------------#
# Application Properties #
# inside ./src/main/resources/application.yml
#-----------------------------------------------------------------------------#
# Turn on debug logging to show ConditionEvaluationReport :
debug: false

# Turn off security for this app, for now.
management:
  security:
    enabled: false
    

## LAB: Create BASIC-Authentication credentials
security:
  user:
    name: user1
    password: s3cr3t
  basic:
    enabled: false


#-----------------------------------------------------------------------------#