#-----------------------------------------------------------------------------#
# Application Properties #
# inside ./src/main/resources/application.yml
#-----------------------------------------------------------------------------#
# Turn on debug logging to show ConditionEvaluationReport :
debug: true

# Create BASIC-Authentication credentials
security:
  user:
    name: user1
    password: s3cr3t

#-----------------------------------------------------------------------------#